name: microcms-build
on: 
  push:
    branches: [main]
  repository_dispatch:
    types: [blog-update]
  # schedule:
  #   - cron: '0,15,30,45 * * * *'
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        options:
          - ビルド
        default: 'ビルド'
        required: true
        description: '処理項目'
env:
  MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
  MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}

jobs:
  build:
    # if: github.event.inputs.mode == 'ビルド' 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: megroponte/microcms-blog
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: |
       npm ci
       npx nuxi generate
       mkdir checkout
    - uses: actions/checkout@v4
      with:
          path:  checkout
    - run: |
       pwd
       cp -R dist/* checkout
       ls -Ra checkout
    - run: | 
       git config user.name "megroponte"
       git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
       cd checkout
       git add .
       git commit -m "generated"
       git push
       
